apiVersion: v1
kind: Service
metadata:
  name: newdep
  namespace: myapp
  labels:
    myapp: hello-app
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008   
  selector:
    app: nginx
  type: NodePort
  
status:
  loadBalancer: {}

