apiVersion: v1
kind: Pod
metadata:
  name: hostpath-dir-pod
spec:
  containers:
    - name: container-a
      image: nginx:latest
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      hostPath:
        path: /temp/data
