apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdep
  namespace: myapp
  labels:
    myapp: hello-app
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp
        image: nginx
