apiVersion: apps/v1
kind: Deployment
metadata:
  name: nitish-dep
  namespace: nitish
  labels: 
    myapp: nitish
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nitish
        image: nginx
