apiVersion: v1
kind: Pod
metadata:
  name: nitish-env
  namespace: fat-bird
  labels: 
    myapp: nitish
    app: nginx

spec:
  containers:
  - name: env-var
    image: nginx
    env:
    - name: Welcome
      value: Welcome to k8s
    - name: Name
      value: "Nitish Ranjan Nayak"
    - name: Age
      value: "24"
    - name: MESSAGE
      value: "$(Welcome) $(Name) $(Age)"
    command: ["echo"]
    args: ["$(MESSAGE)"]