apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-argo
subjects:
 - kind: ServiceAccount
   name: default
   namespace: argo
roleRef:
  kind: ClusterRole
  name: clusterrole-argo
  apiGroup: rbac.authorization.k8s.io      
