apiVersion: v1
kind: Service
metadata:
  name: nitish-service
  namespace: nitish
  labels:
      myapp: nitish
      app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30034
  selector:
    app: nginx
  type: NodePort

